name: Trigger

on:
  workflow_dispatch:

jobs:
  run-signin-test:
    runs-on: ubuntu-latest

    env:
      GOOGLE_EMAIL_VANJA: ${{ secrets.GOOGLE_EMAIL_VANJA }}
      GOOGLE_PASSWORD_VANJA: ${{ secrets.GOOGLE_PASSWORD_VANJA }}
      GOOGLE_TOTPIN_VANJA: ${{ secrets.GOOGLE_TOTPIN_VANJA }}
      HUBSPOT_TOTPIN_VANJA: ${{ secrets.HUBSPOT_TOTPIN_VANJA }}
      CI: true  # Used to detect CI environment in your Java code

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

    - name: Compile and run SignInTest
      run: |
        mkdir -p bin
        javac -d bin -cp ".:$(find . -name '*.jar' | tr '\n' ':')" src/main/java/com/spothopper/SignInTest.java
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' \
          java -cp "bin:$(find . -name '*.jar' | tr '\n' ':')" com.spothopper.SignInTest
